<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Home</name>
   <tag></tag>
   <elementGuidId>2615391a-07af-4922-b915-6f45873e045b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ul.sidebar-menu > li > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='MAIN NAVIGATION'])[1]/following::a[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3477d8a9-e77e-4e36-a498-e5c562583d9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/dashboard/default/index</value>
      <webElementGuid>7f34d414-fdc7-4bef-9c33-01ae5bc7aedb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Home</value>
      <webElementGuid>ae97ddff-eab4-4764-8080-eac4865ed9dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;layout-boxed skin-purple sidebar-mini&quot;]/div[@class=&quot;wrapper&quot;]/aside[@class=&quot;main-sidebar&quot;]/section[@class=&quot;sidebar&quot;]/ul[@class=&quot;sidebar-menu&quot;]/ul[@class=&quot;sidebar-menu&quot;]/li[1]/a[1]</value>
      <webElementGuid>bdef5ee5-7a43-4e30-8327-208591dd130a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MAIN NAVIGATION'])[1]/following::a[1]</value>
      <webElementGuid>70f2ccd9-0049-438d-9eec-fca26c58d50c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign out'])[1]/following::a[2]</value>
      <webElementGuid>c81b7bf6-4eea-4d5d-9c1c-0f4fb0480cf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data Induk Mahasiswa'])[1]/preceding::a[1]</value>
      <webElementGuid>0a0e8e8b-974b-44b4-8861-e1f5b87bdeb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/dashboard/default/index')]</value>
      <webElementGuid>abd74070-15ef-496f-a37d-b962930ae3ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul/ul/li/a</value>
      <webElementGuid>2df83514-db4f-4b0d-b521-2f0842e47360</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/dashboard/default/index' and (text() = 'Home' or . = 'Home')]</value>
      <webElementGuid>0bcc9a9a-d16e-458b-b0b9-1f6d3be40616</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
