<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tanggal Lahir_Dimtgl_lahir</name>
   <tag></tag>
   <elementGuidId>fadb714f-f0f9-4af3-8ebb-044df9528b38</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dim-tgl_lahir</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dim-tgl_lahir']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>62bf9fe0-a21d-4d10-bddd-632302f6a037</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1bbc7fdf-5fbb-43e8-a376-cb7c76505240</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dim-tgl_lahir</value>
      <webElementGuid>1f5cfb04-30f3-46eb-9f6d-2d163b0bc58b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control hasDatepicker</value>
      <webElementGuid>ecf84737-925c-49fd-8f49-5dc9511250d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Dim[tgl_lahir]</value>
      <webElementGuid>40b79674-6bbe-4d6b-b0a8-9c489aa8416a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2003-04-25</value>
      <webElementGuid>2b1cd0e8-380c-4896-8dd4-8559f70d6e58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>27</value>
      <webElementGuid>69937e0c-afd6-4ce2-bedd-2559be841371</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>changemonth</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>16a9e5a5-1cb7-4468-8842-9d41e26e362a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dim-tgl_lahir&quot;)</value>
      <webElementGuid>3deb663a-d6e2-4892-9e16-18f0f2e5c88d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dim-tgl_lahir']</value>
      <webElementGuid>0968f808-6096-44d4-8b07-22f5b60055b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='grid-system1-body']/div[6]/div/div/input</value>
      <webElementGuid>de6119b7-c81d-4b69-a627-1a3929ebcb24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/input</value>
      <webElementGuid>6190ad96-3b54-47ef-b20d-0d498b529d3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'dim-tgl_lahir' and @name = 'Dim[tgl_lahir]']</value>
      <webElementGuid>a88cbd69-ff21-46d0-b568-8e724d7ae36b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
