<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_No. Hp Ayah_Dimno_hp_ayah</name>
   <tag></tag>
   <elementGuidId>c943db39-5cb3-47f7-b389-beba891ae09b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dim-no_hp_ayah</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dim-no_hp_ayah']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bf03c527-b4cc-4d1a-970f-7b9d7faed500</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bf52ce30-e8f8-4884-8bc4-a9eaec337cc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dim-no_hp_ayah</value>
      <webElementGuid>b3b281ca-ad87-421b-9fac-0814c4697e76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>5f2c4915-d3b9-4de9-8765-ce0200b8723a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Dim[no_hp_ayah]</value>
      <webElementGuid>269c3a1e-4f6e-428a-9167-0db3e8d23cdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>081370116288</value>
      <webElementGuid>2ef31ca8-1687-400b-92c1-63e3c931fa79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>f21faaf0-4127-457b-843e-2aea01b1b4e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>No. HP Ayah</value>
      <webElementGuid>fc5eadb2-7862-4a66-81f9-5e38056fcdfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dim-no_hp_ayah&quot;)</value>
      <webElementGuid>db1c4e55-d187-4f82-9d00-7d84ce637d9e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dim-no_hp_ayah']</value>
      <webElementGuid>1b5913fa-1b2f-44a7-9c1a-bbffb7d0ca4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab_4']/div[9]/div/div/input</value>
      <webElementGuid>8368ec72-06d8-4dff-9207-dd42708030fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/input</value>
      <webElementGuid>4c6937c2-9451-4c75-91eb-65e360c92ee6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'dim-no_hp_ayah' and @name = 'Dim[no_hp_ayah]' and @placeholder = 'No. HP Ayah']</value>
      <webElementGuid>223f9102-665c-4443-891a-7e87f0c4893e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
