<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NIK_Dimnik</name>
   <tag></tag>
   <elementGuidId>53b20329-61c2-4e67-9961-47cd7baa7042</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dim-nik</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dim-nik']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>aac82ea3-0385-40d4-b14e-d6ddabea5a31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d38b5c5b-d506-45d9-aceb-bb082e2b618c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dim-nik</value>
      <webElementGuid>b75a25a5-2b39-4026-b2bc-2d9c06b41ea0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>de85106b-994b-4a66-9c62-fcfadf3147b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Dim[nik]</value>
      <webElementGuid>a2d130c5-2ba9-4314-b7cf-9b5d7c145040</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nomor Induk Kependudukan</value>
      <webElementGuid>8d638d0f-7cbd-4994-9fab-e1d6b36c97b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>54e63625-3236-401c-bcbe-09ca7b892800</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dim-nik&quot;)</value>
      <webElementGuid>8ee5a969-3256-4981-ab7a-ed64d1536ca8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dim-nik']</value>
      <webElementGuid>87e7fc26-f6ec-4eec-874e-da51dcebeda4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='grid-system1-body']/div[3]/div/input</value>
      <webElementGuid>4b9c7bde-f951-46a9-89af-9a7894d3ced1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>40622a79-0aca-4d94-9f4d-ba79531b6e84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'dim-nik' and @name = 'Dim[nik]' and @placeholder = 'Nomor Induk Kependudukan']</value>
      <webElementGuid>9073ef38-9ddd-4f24-9c2c-eadd4cb1ffdf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
