<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Jl. Lapangan Golf Girsang</name>
   <tag></tag>
   <elementGuidId>92d82a8b-e3b2-45ba-aec5-5e9aef5c0642</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dim-alamat_orangtua</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='dim-alamat_orangtua']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>30f8208f-9ddc-4789-9757-7f34d31f589f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dim-alamat_orangtua</value>
      <webElementGuid>4eac9819-d6c8-4a0d-9404-133a3e6908c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>545c3b93-3fde-4957-8706-b0674ed7f80d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Dim[alamat_orangtua]</value>
      <webElementGuid>0d7b3a98-f689-4d8e-aed4-abe2b3b4aec8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>05ab1f9f-4789-429d-8c30-5422e13f9fb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Jl. Lapangan Golf Girsang </value>
      <webElementGuid>5b9cc661-419c-42b4-b300-35c7c6e9ed2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dim-alamat_orangtua&quot;)</value>
      <webElementGuid>93801cf1-27e8-47b7-953b-d48c56d33516</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='dim-alamat_orangtua']</value>
      <webElementGuid>0a7e88a6-c0b1-4a64-b5d8-fc7e9203eb5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab_4']/div[11]/div/textarea</value>
      <webElementGuid>d89ab8f9-1c75-449f-b65c-81e5c76f6c05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alamat Orangtua'])[1]/following::textarea[1]</value>
      <webElementGuid>dfdbd50c-7485-46b6-84e8-7a9e12b63599</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No. Hp Ibu'])[1]/following::textarea[1]</value>
      <webElementGuid>20abc5c5-d2f2-417b-936d-4c7a4bae75a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pendidikan Ayah'])[1]/preceding::textarea[1]</value>
      <webElementGuid>c97397dc-644f-4310-acee-775b1c39c69e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pekerjaan Ayah'])[1]/preceding::textarea[1]</value>
      <webElementGuid>148f3d0f-349a-4867-8b67-1bc463588d9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/textarea</value>
      <webElementGuid>c9db4c25-3831-4954-92db-34aded1bf7bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'dim-alamat_orangtua' and @name = 'Dim[alamat_orangtua]' and (text() = 'Jl. Lapangan Golf Girsang ' or . = 'Jl. Lapangan Golf Girsang ')]</value>
      <webElementGuid>1ef03425-0efd-4e02-86fa-31a1b34dadc3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
