<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_tambah sekolah</name>
   <tag></tag>
   <elementGuidId>5e865e37-ec14-42c5-96b8-3676e5801eb2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.col-sm-8 > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tab_5']/div[5]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8f261f68-a257-4bac-a255-27cd53c001b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/mref/asal-sekolah/add</value>
      <webElementGuid>a1def1c2-4c31-4b99-8edf-924dc3076d07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> + tambah sekolah </value>
      <webElementGuid>9acf78c5-a9a3-45e2-b12b-c91d0d03bd07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab_5&quot;)/div[@class=&quot;col-sm-8&quot;]/a[1]</value>
      <webElementGuid>84db1b7f-93f6-4a8b-a86c-e49849f7c006</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab_5']/div[5]/a</value>
      <webElementGuid>d07090a5-e286-4453-8d23-26b7123a7161</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'+ tambah sekolah')]</value>
      <webElementGuid>26531115-5af0-47d4-a016-01264def19fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Asal Sekolah'])[1]/following::a[1]</value>
      <webElementGuid>5840847f-6b45-4111-bd5b-10273be9f51d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No. Ijazah SMA'])[1]/following::a[1]</value>
      <webElementGuid>9c038825-24d6-4272-b853-08f46077d671</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[3]/preceding::a[1]</value>
      <webElementGuid>23674b8d-278a-4af2-bb0a-47b193c58be6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Version'])[1]/preceding::a[1]</value>
      <webElementGuid>441c8678-fa52-4e10-9c84-354a0d13a92a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='+ tambah sekolah']/parent::*</value>
      <webElementGuid>e4af018d-158c-4405-ab52-f37c8079efcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/mref/asal-sekolah/add')]</value>
      <webElementGuid>84a9e81d-275e-4072-b152-4a95fa8f18d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/a</value>
      <webElementGuid>8c092c49-67f3-4486-98da-e8c3f35e05bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/mref/asal-sekolah/add' and (text() = ' + tambah sekolah ' or . = ' + tambah sekolah ')]</value>
      <webElementGuid>9362af86-2fb1-44ab-8c56-e114df26f64b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
