<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Asal Sekolah_asal_sekolah_id-fake</name>
   <tag></tag>
   <elementGuidId>f051c63e-7405-4ae2-a2f6-ee41e5f53a3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#w1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='w1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>43a0cfdc-cd28-4a7d-bed4-cd138de34616</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>46aa942f-63e4-41e9-b15c-3c31025147c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>w1</value>
      <webElementGuid>808dd3e0-f9eb-4462-a819-0d0578fcb2f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>typeahead tt-input</value>
      <webElementGuid>7420fcff-41e8-424c-a8ab-ac132bc73b1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>asal_sekolah_id-fake</value>
      <webElementGuid>dba914d6-2750-4e81-ac4c-32dc22076cfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Asal Sekolah</value>
      <webElementGuid>ffb85bcd-c4b5-4cd5-9b89-52bf0a69be82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>af0b9d1b-946e-4012-8153-09ee275afe44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>fcd4195f-ceb3-4184-abbf-304f3947bc59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>61fccd25-c067-4114-93a8-134c2ab20a5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;w1&quot;)</value>
      <webElementGuid>d1508e85-27de-479d-8ffc-2f3f672ab1f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='w1']</value>
      <webElementGuid>bfbbe0bc-616b-499b-937e-393ea6e92c73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab_5']/div[5]/span/input</value>
      <webElementGuid>a1345247-23a0-4fe0-a91c-aad01b646a85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>627c185e-50d1-4b65-af5b-b913e22c2dc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'w1' and @name = 'asal_sekolah_id-fake' and @placeholder = 'Asal Sekolah']</value>
      <webElementGuid>56b217b6-0f3c-4707-8d33-298d0d27d15d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
